name=HiTECH R4 Wifi Manager
version=2026.6.20
author=HiTECH Corporation
maintainer=Nguyen Thai Minh <hitech.ntm0911@gmail.com>
sentence=Professional WiFi Manager and Captive Portal for Arduino Uno R4 WiFi.
paragraph=Enables dynamic WiFi configuration via a web interface. Uses Full Non-Blocking Architecture and Zero Fragment memory handling.
category=Communication
url=https://github.com/HiTECH-Corporation/R4-WifiManager
architectures=renesas_uno
includes=HiTECH_R4_Wifi_Manager.h